clean some shell scripts, get rid of requires on make

diff --git a/renew-dummy-cert b/renew-dummy-cert
--- a/renew-dummy-cert
+++ b/renew-dummy-cert
@@ -1,21 +1,21 @@
-#!/bin/bash
+#!/bin/sh
 
 if [ $# -eq 0 ]; then
-	echo $"Usage: `basename $0` filename" 1>&2
-	exit 1
+    echo $"Usage: `basename $0` filename" 1>&2
+    exit 1
 fi
 
 PEM=$1
-REQ=`/bin/mktemp /tmp/openssl.XXXXXX`
-KEY=`/bin/mktemp /tmp/openssl.XXXXXX`
-CRT=`/bin/mktemp /tmp/openssl.XXXXXX`
+REQ=$(/bin/mktemp /tmp/openssl.XXXXXX)
+KEY=$(/bin/mktemp /tmp/openssl.XXXXXX)
+CRT=$(/bin/mktemp /tmp/openssl.XXXXXX)
 NEW=${PEM}_
 
 trap "rm -f $REQ $KEY $CRT $NEW" SIGINT
 
 if [ ! -f $PEM ]; then
-	echo "$PEM: file not found" 1>&2
-	exit 1
+    echo "$PEM: file not found" 1>&2
+    exit 1
 fi
 
 let -a SERIAL=0x$(openssl x509 -in $PEM -noout -serial | cut -d= -f2)
@@ -23,7 +23,7 @@ let SERIAL++
 
 umask 077
 
-OWNER=`ls -l $PEM | awk '{ printf "%s.%s", $3, $4; }'`
+OWNER=$(ls -l $PEM | awk '{ printf "%s.%s", $3, $4; }')
 
 openssl rsa -inform pem -in $PEM -out $KEY
 openssl x509 -x509toreq -in $PEM -signkey $KEY -out $REQ
@@ -39,4 +39,3 @@ mv -f $NEW $PEM
 rm -f $REQ $KEY $CRT
 
 exit 0
-
